makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-slate
include:
  - assets
  - README.md
- name: GitHub Pages action
uses: peaceiris/actions-gh-pages@v4.0.0
- name: Doxygen Action
uses: mattnotmitt/doxygen-action@1.9.8
                        
